
default_platform(:ios)

platform :ios do

lane :build_and_test do
  build
  test
end

  desc "test lane for bitrise integration "
  lane :build do
    gym(
    project: "BitriseIntegration.xcodeproj",
    configuration: "Debug",
    scheme: "BitriseIntegration",
    silent: true,
    clean: true,
    skip_archive: true,
    export_method: "development",
    skip_codesigning: true   # Disable code signing for development builds
  )
  end

desc "run unit test"
lane :test do
  scan(
	scheme: "BitriseIntegration",
	device: "iPhone 15"
)
end
end